apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:GoSquid-io/gitops.git
    path: registry/allfarms/components/kubefirst
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
