metaphor:
  image:
    repository: 366414632657.dkr.ecr.ap-southeast-1.amazonaws.com/metaphor
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    hosts:
      - host: metaphor-production.2farm.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-production.2farm.dev
  metaphor:
    host: https://metaphor-production.2farm.dev/api
    console: https://kubefirst.2farm.dev
