---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-publish-permissions-sync
  namespace: argo
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::366414632657:role/ecr-publish-permissions-sync-allfarms'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-publish-permissions-sync
  namespace: argo
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-publish-permissions-sync
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-publish-permissions-sync
subjects:
  - kind: ServiceAccount
    name: ecr-publish-permissions-sync
    namespace: argo
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: ecr-publish-permissions-sync
  namespace: argo
spec:
  # Run every 6 hours.
  schedule: '0 */6 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-publish-permissions-sync
          restartPolicy: OnFailure
          containers:
            - name: ecr-publish-permissions-sync
              image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
              imagePullPolicy: IfNotPresent
              args:
                - sync-ecr-token
                - --namespace
                - argo
                - --region
                - ap-southeast-1
                - --registry-url
                - 366414632657.dkr.ecr.ap-southeast-1.amazonaws.com
