apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-metaphor
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  replicas: 1
  template:
    spec:
      organization: <GITHUB_OWNER>
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true
      resources:
        requests:
          cpu: '2'
          memory: '4Gi'
        limits:
          cpu: '2'
          memory: '8Gi'
