apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.22.0
    helm:
      parameters:
        - name: server.route.host
          value: vault.2farm.dev
        - name: 'server.ingress.hosts[0].host'
          value: vault.2farm.dev
      values: |-
        server:
          serviceAccount:
            create: true
            name: vault
            annotations:
              eks.amazonaws.com/role-arn: 'arn:aws:iam::366414632657:role/vault-allfarms'
          affinity: ""
          ha:
            enabled: true
            replicas: 3
            config: |
              ui = true
              listener "tcp" {
                tls_disable     = 1
                address         = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "dynamodb" {
                ha_enabled = "true"
                region = "ap-southeast-1"
                table = "vault-backend-allfarms"
              }
              seal "awskms" {
                region     = "ap-southeast-1"
                kms_key_id = "c4301863-6c39-41fd-b43f-68b6fdc0bc81"
              }
              service_registration "kubernetes" {}
          ingress:
            enabled: true
            annotations: 
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingressClassName: "nginx"
            pathType: Prefix
            # When HA mode is enabled and K8s service registration is being used,
            # configure the ingress to point to the Vault active service.
            # activeService: true
            hosts:
              - host: vault.2farm.dev
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.2farm.dev
          ui:
            enabled: true
            serviceType: "ClusterIP"
            serviceNodePort: null
            externalPort: 8200
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
