apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_GIT_URL>
    path: registry/<CLUSTER_NAME>/components/shared/rabbitmq
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
